### ISSUE TITLE
Ceate a new Tensor class as the main data structure 

### ISSUE THREAD

**Issue by scitorch** [scitorch/scitorch#9]
Like the tensor in PyTorch or the ndarray in NumPy a 'standard' class could be useful for computations. This could be very helpful when overloading the algebraic operations to also work with physical dimensions. 

The basic idea is that a SciTorch tensor is a PyTorch tensor if only a scalar, list/vector, matrix or tensor is given as an input BUT it should be it's own 'structure' if there is also a dimensionality given as an input. This also makes transitioning to PyTorch tensors or NumPy arrays easy as it basically is just a PyTorch tensor + a bit more information.

**Comment by christophfritz** [comment]
This will be available with the first alpha release. The Tensor class now consists of a value and a dimensionality.
